package com.codeops.vault.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/**
 * Base entity providing UUID primary key and audit timestamps for all Vault entities.
 *
 * <p>All concrete entities extend this mapped superclass to inherit a UUID primary key
 * generated by the JPA provider, plus {@code createdAt} and {@code updatedAt} timestamps
 * managed automatically via {@link PrePersist} and {@link PreUpdate} lifecycle callbacks.</p>
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        updatedAt = Instant.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }
}
